name = "yt-stream-worker"
main = "worker/worker.js"
compatibility_date = "2025-12-01"
account_id = "ba965c4096a669be2ff149b0ed864645"

kv_namespaces = [
  { binding = "STREAMS", id = "8a84f5a9b4ad41ab8f1ec6293553f86d" },
  { binding = "STREAM_STATUS", id = "8b031e88d7a84e6c9d626b8f23689965" }
]
